@startuml system-context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

together{
Person(analyst, "Analyst")
Person(admin, "Admin")
Person(user, "User")
}
together{
Container_Ext(broker, "Message-broker")
Container_Ext(movies_service, "Movies service")
}
System_Boundary(ugc_service, "UGC"){
    together{
    Container(give_review, "Create review")
    Container(give_events, "Write events")
    Container(delete_review, "Delete review")
    Container(update_review, "Update review")
    }
    Container(sing_in, "Auth controller")
}

together{
ContainerDb(ugc_database, "UGC database")
ContainerDb(event_database, "Events database")
}

Rel(user, give_review, "Review message", "JSON,HTTPS")
Rel(give_review, sing_in, "User info", "JWT")
Rel(sing_in, ugc_database,)
Rel(give_review, event_database, "Event info", "SQL")
Rel(give_events, event_database, "Event info", "SQL")
Rel(broker, give_events, "Event info", "JSON,HTTPS")


@enduml
