version: '3.9'

services:

  logstash:
    image: logstash:8.10.2
    depends_on:
      - elasticsearch
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./ugc/deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - ./ugc/deploy/esdata:/tmp/elasticsearch/data

  kibana:
    image: kibana:8.10.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./ugc/deploy/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ugc/deploy/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - /tmp/logs/nginx/:/var/log/nginx/
    # depends_on:
    #   - ugc-service
    ports:
      - 80:80

  filebeat:
    build:
      context: ./ugc/filebeat
    container_name: filebeat
    volumes:
      - ./src/logs/:/src/logs
      - /tmp/logs/nginx:/var/log/nginx:ro
    depends_on:
      - elasticsearch
      - kibana
      - nginx
      - logstash
      # - ugc-service
