openapi: 3.0.0
info:
  title: UGC Events API
  description: API для обработки событий пользовательского интерфейса и плеера.
  version: "1.0.0"
servers:
  - url: /ugc/
paths:
  /click_event/{event_type}:
    post:
      summary: "Post clicking event"
      parameters:
        - name: event_type
          in: path
          description: "Type of click event"
          required: true
          schema:
            type: string
            enum: [ click, close, to_url ]
        - name: jwt_token
          in: query
          description: "Access token"
          required: true
          schema:
            type: string
        - name: event_dt
          in: query
          description: "Time of event"
          required: true
          schema:
            type: string
            format: date-time
        - name: url
          in: query
          description: "URL for moving"
          required: false
          schema:
            type: string
      responses:
        '200':
          description: "Successful writing"
        '400':
          description: "Invalid request, missing required parameters"
        '401':
          description: "Unauthorized access, invalid or missing JWT token"
        '403':
          description: "Access denied, insufficient permissions to perform the operation"
        '404':
          description: "Specified resource not found"
        '500':
          description: "Internal server error"

  /player_event/{event_type}:
    post:
      summary: "Post videoplayer event"
      parameters:
        - name: event_type
          in: path
          description: "Type of event"
          required: true
          schema:
            type: string
            enum: [ stop, start, repeat, settings ]
        - name: event_dt
          in: query
          description: "Time of event"
          required: true
          schema:
            type: string
            format: date-time
        - name: movie_url
          in: query
          description: "URL to filmwork"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Successful writing"
        '400':
          description: "Invalid request, missing required parameters"
        '401':
          description: "Unauthorized access, invalid or missing JWT token"
        '403':
          description: "Access denied, insufficient permissions to perform the operation"
        '404':
          description: "Specified resource not found"
        '500':
          description: "Internal server error"
