version: '3.0'

services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=ugc_user
      - POSTGRES_PASSWORD=ugc_pass
      - POSTGRES_DB=ugc
    ports:
      - "5432:5432"

  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://ugc_user:ugc_pass@db:5432/ugc
