version: '3.0'

services:

  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=ugc_user
      - POSTGRES_PASSWORD=ugc_pass
      - POSTGRES_DB=ugc
    ports:
      - "5432:5432"
