version: '3.5'

services:
  zookeeper:
    image: zookeeper:3.8
    container_name: test_zookeeper
    hostname: zookeeper
    networks:
      - benchmark_tests

  clickhouse-node1:
    image: clickhouse/clickhouse-server:23
    container_name: test-clickhouse-node1
    hostname: test-clickhouse-node1
    volumes:
      - ./clickhouse_nodes/node1:/etc/clickhouse-server
    depends_on:
      - zookeeper
    # ports:
    #   - "8123:8123"
    #   - "9000:9000"
    networks:
      - benchmark_tests

  clickhouse-node2:
    image: clickhouse/clickhouse-server:23
    container_name: test-clickhouse-node2
    hostname: test-clickhouse-node2
    volumes:
      - ./clickhouse_nodes/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper
    networks:
      - benchmark_tests

  clickhouse-node3:
    image: clickhouse/clickhouse-server:23
    container_name: test-clickhouse-node3
    hostname: test-clickhouse-node3
    volumes:
      - ./clickhouse_nodes/node3:/etc/clickhouse-server
    depends_on:
      - zookeeper
    networks:
      - benchmark_tests
  
  clickhouse-bench-test:
    build: ./clickhouse_bench_test
    container_name: clickhouse_bench_test
    env_file:
      - ../../.env
    depends_on:
      - zookeeper
      - clickhouse-node1
      - clickhouse-node2
      - clickhouse-node3
    networks:
      - benchmark_tests
    

networks:
  benchmark_tests:
    driver: bridge
