version: '3.5'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse_benchmark-server
    ports: 
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./clickhouse_settings/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse_db:/var/lib/clickhouse

  vertica:
    image: jbfavre/vertica:latest 
    container_name: vertica
    env_file:
      - ../../.env
    ports:
      - '5433:5433'
  
  postgres:
    container_name: postgres_benchmark
    image: postgres:13
    restart: always
    env_file:
      - ../../.env
    ports: 
      - '5434:5432'
    environment:
      POSTGRES_DB: bench_db
      POSTGRES_USER: bench_user
      POSTGRES_PASSWORD: bench_pass
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_bench_vol:/var/lib/postgres/data

  mongodb:
    image: mongo
    container_name: mongo_single_benchmark
    environment:
      MONGO_INITDB_ROOT_USERNAME: bench_user
      MONGO_INITDB_ROOT_PASSWORD: bench_pass
      MONGO_INITDB_DATABASE: bench_db
    ports: 
      - '27018:27017'
    volumes:
      - mongo_single_bench_vol:/data
    restart: "always"



volumes:
  clickhouse_db:
  postgres_bench_vol:
  mongo_single_bench_vol:
