name: UGC service python application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Edit config
        run: git config --global user.email "usikov.dv@gmail.com" && git config --global user.name "konarlook"

      - name: Version patch
        run: npm version 0.1.$GITHUB_RUN_ID

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide
          pip install -f ugc/tests/requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=18 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest ugc/tests/functional

      - name: Telegram natification
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: New 0.1.${{ github.run_id }} version publish
